<!DOCTYPE html>
<html lang="en"></html>
<head>
  <meta charset="utf-8">
  <title>{{ twigdata }} - ZF2 Skeleton Application </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--
  <Le>styles </Le>
  -->
  <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
  <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
  <!--
  <Scripts> </Scripts>
  -->
  <!--[if lt IE 9]>
  <script type="text/javascript" src="/js/html5shiv.js"></script>
  <![endif]-->
  <!--[if lt IE 9]>
  <script type="text/javascript" src="/js/respond.min.js"></script>
  <![endif]-->
  <script type="text/javascript" src="/js/jquery.min.js"></script>
  <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
  <nav role="navigation" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a href="/" class="navbar-brand"><img src="/img/zf2-logo.png" alt="Zend Framework 2">Skeleton Application</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
        </ul>
      </div>
      <!--/.nav-collapse 
      -->
    </div>
  </nav>
  <div class="container"><?php echo $this->content; ?>
    <hr>
    <footer>
      <p>© 2005 - 2013 by Zend Technologies Ltd. All rights reserved.</p>
    </footer>
  </div>
  <!--/container 
  -->
</body>